# See example script at https://github.com/JuliaLang/Example.jl
language: julia
env:
 - CONDA_JL_VERSION=2

os:
  - linux
#  - osx

julia:
  - 1.6

branches:
  only:
    - master

matrix:
  - PYTHON=Conda-python

matrix:
  allow_failures:
    - julia: 1.6

notifications:
  email: false

git:
  depth: 99999999


jobs:
    include:
      - stage: "Testing"
        script:
          - julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test();'
      - stage: "Documentation"
        script:
          - julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build(); include("docs/make.jl");'
        after_success: skip
