name: Documentation
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  docs:
    name: Documenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - run: |
          pip install --upgrade pip
          pip install --upgrade cython
          pip3 install numpy matplotlib astropy ultranest
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
